config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :groups do
    resources :members, only: [:create, :index, :edit] do
      resources :member_rewards, only: [:index, :update]
      resources :member_punishments, only: [:index, :update]
    end
    resources :rewards, only: [:index, :update]
    resources :punishments, only: [:index, :update]
    resources :tasks, only: [:new, :create]
    # resources :messages, only: [:show, :create]
  end

  resources :progresses, only: [:edit, :update]
  resources :members, only: [:show, :destroy, :edit]


  resources :chats, only: [:index, :show] do
    resources :messages, only: [:index, :show, :create]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :tasks, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :punishments, dependent: :destroy
  has_one :chat, dependent: :destroy

  accepts_nested_attributes_for :tasks, allow_destroy: true
  accepts_nested_attributes_for :punishments, allow_destroy: true
  accepts_nested_attributes_for :rewards, allow_destroy: true

  validates :name, presence: true
  validates :tasks, presence: true

  has_one_attached :photo

end

# :members, allow_destroy: true, uniqueness: true

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_groups = RankingCalculation.group_with_avances(current_user.id)
  end

  def show
    @group = Group.find(params[:id])
    @members = Member.where(group: @group)
    @users = User.joins(:members).where(members: { group_id: @group })
    # @tasks = Task.where(group: @group)
    @tasks = @group.tasks if @group.tasks.present?
    @task = Task.new
    @reward = Reward.new
    @punishment = Punishment.new
    ranking_calculation = RankingCalculation.new(@tasks, @group.id)
    @my_index = ranking_calculation.my_index(current_user.username)
    # For progresses, we're going to find each progress in the view directly
  end

  def new
    @group = Group.new
    @task = Task.new
    @group.tasks.build if @group.tasks.empty?
    @group.rewards.build if @group.rewards.empty?
    @group.punishments.build if @group.punishments.empty?
    @group.members.build if @group.members.empty?
  end

  def create
    @group = Group.new(group_params)
    @user = current_user
    if @group.save
      @admin = Member.new(user_id: @user.id, group_id: @group.id, admin: true)
      @admin.save

      ### Creating Progress instances with 0% completion at the initialization of the group ###
      @tasks = Task.where(group: @group)
      @members = Member.where(group: @group)
      @tasks.each do |task|
        @members.each do |member|
          progress = Progress.new(task_id: task.id, member_id: member.id, completion: 0.00)
          progress.save
        end
      end

      ### Creando Chat
      @chat = Chat.new(group_id: @group.id)
      @chat.save!

      redirect_to group_path(@group.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def edit
    @group = Group.find(params[:id])
    @group.tasks.build if @group.tasks.empty?
    @group.rewards.build if @group.rewards.empty?
    @group.punishments.build if @group.punishments.empty?
    @group.members.build if @group.members.empty?
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name, :photo,
                                  tasks_attributes:[:id, :name, :unit, :quantity, :_destroy],
                                  punishments_attributes: [:id, :name, :_destroy],
                                  rewards_attributes: [:id, :name, :_destroy])
  end
end

app/views/groups/edit.html.erb
<h1>Edit group here</h1>

<%= simple_form_for @group do |f| %>
  <%= f.input :name, required: true, placeholder: @group.name %>

  <h3>Tasks</h3>
  <%= f.fields_for :tasks do |t| %>
    <% Task.where(group: @group).each do |task| %>
      <%= t.input :name, required: true, placeholder: task.name %>
      <%= t.input :unit, required: true, collection: ["km", "unit2", "unit3"], include_blank: "Select unit type" %> <!-- Dropdown menu -->
      <%= t.input :quantity, required: true, placeholder: task.quantity %>
    <% end %>
  <% end %>

  <h3>Rewards</h3>
  <%= f.fields_for :rewards do |r| %>
    <% Reward.where(group: @group).each do |reward| %>
      <%= r.input :name, required: true, placeholder: reward.name %>
    <% end %>
  <% end %>

  <h3>Punishments</h3>
  <%= f.fields_for :punishments do |p| %>
    <% Punishment.where(group: @group).each do |punishment| %>
      <%= p.input :name, required: true, placeholder: punishment.name %>
    <% end %>
  <% end %>

  <%= f.submit "Create Group" %>
<% end %>

<%= link_to "Back", groups_path %>

app/views/groups/index.html.erb
<section class="section-index-groups">
  <div class="section__title--groups">
    <div class="line-groups"></div>
      <h2 class="section__h2--groups">Your groups</h2>
    <div class="line-groups"></div>
  </div>

  <div class="container-groups">
    <% @user_groups.each do |group| %>
      <div class="card-group">
        <%= link_to group_path(group.id), class: "card-group-title" do %>
          <% if group.photo.present? && group.photo.key.present? %>
            <%= cl_image_tag(group.photo.key, class: "picture-profile-group") %>
          <% else %>
            <%= image_tag "Držení Za Ruce.jfif", class: "picture-profile-group" %>
          <% end %>

          <div class="name-group-description">
            <h3><%= group.name %></h3>
            <p>Progress:</p>

            <div class="progress progress-bar-index-group w-100" style="background-color: #bbbbbbdd;" role="progressbar" aria-label="Basic example" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-bar" style="width: <%= group.avg_completion_per_task_member %>%">
                  <%= group.avg_completion_per_task_member.round(2) %> %
              </div>
            </div>

          </div>
        <% end %>

        <div class="button-delete-group">
          <% if Member.find_by(user_id: current_user.id, group_id: group.id ).admin %>
            <%= link_to group_path(group.id),
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                        class: "delete-button" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-square-x">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14z" />
                <path d="M9 9l6 6m0 -6l-6 6" />
              </svg>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="buttons-index-groups">
    <%= link_to "Create Group", new_group_path, class: "create-group-index" %>


    <button class="button-delete-group-toogle" data-controller="toogle-delete-group" data-action="click->toogle-delete-group#showButtonsDeletes">
      Delete Group
    </button>


  </div>
</section>

app/views/groups/new.html.erb
<section class="section-new-group">

  <div class="top">

    <div class="section__title--groups">
      <div class="line-groups"></div>
        <h2 class="section__h2--groups">New Group</h2>
      <div class="line-groups"></div>
    </div>
  </div>


  <%= simple_form_for @group, html: { class: "simple-form-new-group" } do |f| %>
    <div class="row col-12 mb-2">
      <h3>Group Name</h3>
        <%= f.input :name, required: true, input_html: { placeholder: 'Name', class: 'center-placeholder' }, label: false %>
    </div>

    <div class="w-100">
      <h3>Tasks</h3>
      <div data-controller="new-task">
        <div data-new-task-target="taskForm">
          <%= f.fields_for :tasks do |t| %>
            <div class="w-100 task-form" >
              <div class="row col-12" >
                <div class="col-8" data-new-task-target="taskName">
                  <%= t.input :name, required: true, input_html: { placeholder: 'Run', class: 'center-placeholder' }, label: false %>
                </div>
                <div class="col-2" id="quantity">
                  <%= t.input :quantity,
                              required: true,
                              input_html: {
                                placeholder: '10',
                                class: 'center-placeholder',
                                min: 0,
                                type: 'number' }, label: false %>
                </div>
                <div class="col-2">
                  <%= t.input :unit, required: true, input_html: { placeholder: 'Km', class: 'center-placeholder',  }, label: false %>
                </div>
                <button class="btn d-none trash-new-task"
                        data-new-task-target="deleteTask"
                        data-action="click->new-task#removeTask">
                  <div>
                    <i class="fa-solid fa-trash"></i>
                  </div>
                </button>
              </div>


            </div>
          <% end %>

        </div>

        <div data-new-task-target="placeholder"></div>

        <div class="d-flex justify-content-between w-100">
          <div class="col-12" data-new-task-target="addButton">
            <button class="addTaskButton" data-action="click->new-task#addTask">Add another task</button>
          </div>
        </div>
      </div>
    </div>




    <div class="mt-3 mb-3 w-100">
      <h3>Rewards</h3>
      <%= f.fields_for :rewards do |r| %>
        <div class="row col-12">
          <%= r.input :name, required: true, input_html: { placeholder: 'Reward for first place', class: 'center-placeholder' }, label: false %>
        </div>
      <% end %>
      <h3>Punishments</h3>
      <%= f.fields_for :punishments do |p| %>
        <div class="row col-12">
          <%= p.input :name, required: true, input_html: { placeholder: 'Punishment for last place', class: 'center-placeholder' }, label: false %>
        </div>
      <% end %>
      <div data-controller="upload-label">
      <h3 >Group Photo</h3>
        <%= f.label :photo, "Upload photo", class: 'custom-file-upload', data: { upload_label_target: 'Label' } %>
        <%= f.input :photo, as: :file, label: false, input_html: { class: 'center-placeholder d-none', data: { upload_label_target: "inputField" , action: "input->upload-label#update"} } %>
      </div>
    </div>

    <%= f.submit "Create Group", class:"drk-button"%>
  <% end %>
  <%= link_to "Go back", root_path, class: "button-goback-newgroup" %>
</section>

app/views/groups/show.html.erb
<section class="section-group-detail">

  <section class="title-group-detail">
    <div class="line-groups"></div>
    <h3 class="title-group-detail-name">
      <%= @group.name %>
    </h3>
    <div class="line-groups"></div>
  </section>

  <section class="header-div-container-buttons">
    <div class="task-div-container-header-buttons">
      <div data-controller="group-member" class="group-member" data-group-member-group-id-value="<%= @group.id %>">
        <%= render 'shared/linkShare' %>
      </div>

      <%= link_to "Messages", chat_messages_path(Chat.find_by(group_id: @group.id).id), class: "task-div-container-header-chat" %>
    </div>
  </section>

  <section class="task-section-container">
    <div class="title-group-detail">
      <div class="line-groups"></div>
        <h3 class="title-group-detail-name">
          Task
        </h3>
      <div class="line-groups"></div>
    </div>

    <div class="task-view-container">
      <% if @tasks.present? %>
        <% @tasks.each do |task| %>

          <div class="div-container-individual-task">
            <div class="title-container-individual-task">
              <h5><%= task.name %></h5>
              <p>
                <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-target-arrow"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M12 7a5 5 0 1 0 5 5" /><path d="M13 3.055a9 9 0 1 0 7.941 7.945" /><path d="M15 6v3h3l3 -3h-3v-3z" /><path d="M15 9l-3 3" /></svg>

                <%= task.quantity %>
                <%= task.unit %>
              </p>
            </div>

            <% @members.each do |member| %>
              <% progress = Progress.find_by(member_id: member.id, task_id: task.id) %>
              <div class="container-bar-progress-indivual-task" data-controller="edit-progress">
                <div class="header-container-progress-individual-task">


                  <% if progress.member.user.id == current_user.id %>
                    <div class="title-container-username-editprogress">
                      <h5 class="username-container-indivual-task">
                        <%= User.find(member.user_id).username %>
                      </h5>

                      <div class="icons-edit-progress" data-action="click->edit-progress#toggle">
                        <% if progress.present? %>
                          <% if progress.completion.round(2) >= 100.00 %>
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checkbox"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 11l3 3l8 -8" /><path d="M20 12v6a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h9" /></svg>
                          <% else %>
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-edit"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" /><path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" /><path d="M16 5l3 3" /></svg>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                    <div class="barprogress-task-indiviaul">
                      <div class="progress" style="background-color: #bbbbbbdd;" data-action="click->edit-progress#toggle">
                        <div class="progress-bar" role="progressbar" style="width: <%= progress.completion.round(2) %>%;">
                          <%= progress.completion.round(2) %> %
                        </div>
                      </div>
                    </div>

                  <% else %>
                    <div class="title-container-username-editprogress">
                      <h5 class="username-container-indivual-task">
                        <%= User.find(member.user_id).username %>
                      </h5>

                      <div class="icons-edit-progress">
                        <% if progress.present? %>
                          <% if progress.completion.round(2) >= 100.00 %>
                            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-checkbox"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 11l3 3l8 -8" /><path d="M20 12v6a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h9" /></svg>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                    <div class="barprogress-task-indiviaul">
                      <div class="progress" style="background-color: #bbbbbbdd;">
                        <div class="progress-bar" role="progressbar" style="width: <%= progress.completion.round(2) %>%;">
                          <%= progress.completion.round(2) %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>

                <div class="d-none container-edit-progress" data-edit-progress-target="togglableElement">
                  <%= render "progresses/editprogress", progress: progress %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="add-group-task" data-controller="add-group-task">
          <button data-action="click->add-group-task#addTask" class="btn btn-primary add-new-task-individualview">
            Add Task
          </button>
          <div class="d-none" data-add-group-task-target="togglableElement">
            <%= render "shared/addnewtask", task: @task %>
          </div>
        </div>
      <% else %>
        <p>No tasks available</p>
      <% end %>
    </div>
  </section>

  <section class="position-group-container">
    <div class="title-group-detail">
      <div class="line-groups"></div>
        <h3 class="title-group-detail-name">
          Your position
        </h3>
      <div class="line-groups"></div>
    </div>


    <div class="container-targets-group-position">
      <%= link_to group_members_path(@group), class: "target-position-group-individual" do %>
        <div class="target-position">
          <div class="icon-group-position">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-users-group">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <path d="M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
              <path d="M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1" />
              <path d="M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
              <path d="M17 10h2a2 2 0 0 1 2 2v1" />
              <path d="M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
              <path d="M3 13v-1a2 2 0 0 1 2 -2h2" />
            </svg>
          </div>

          <div class="data-position-group-indivual" data-controller="place">
            <div data-place-target="output" class="p-indexplace"><p><%= @my_index %></p></div>
            <p>Out of <%= @members.size unless @members.nil? %></p>
          </div>
        </div>
    <% end %>

    </div>
  </section>

  <section class="rewards-punishments-container">
    <div class="title-group-detail">
      <div class="line-groups"></div>
        <h3 class="title-group-detail-name">
          Incentives
        </h3>
      <div class="line-groups"></div>
    </div>

    <div class="target-rewards-container">
      <div class="container-title-reward">
        <h5 class="title-reward">
          Rewards
        </h5>
        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-award"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 9m-6 0a6 6 0 1 0 12 0a6 6 0 1 0 -12 0" /><path d="M12 15l3.4 5.89l1.598 -3.233l3.598 .232l-3.4 -5.889" /><path d="M6.802 12l-3.4 5.89l3.598 -.233l1.598 3.232l3.4 -5.889" /></svg>
      </div>

      <div class="container-all-rewards">
        <% @group.rewards.each do  |reward| %>
          <p>
            <%= reward.name %>
          </p>
        <% end %>
      </div>


      <div data-controller="add-group-reward" class="add-group-reward">
        <button data-action="click->add-group-reward#addReward" class="btn btn-primary button-reward">
          Change Reward
        </button>
        <div data-add-group-reward-target="togglableElement" class="d-none">
          <% unless @reward.nil? %>
            <%= render "shared/addnewreward", reward: @reward %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="target-punishments-container">
      <div class="container-title-punishment">
        <h5 class="title-punishment">
          Punishments
        </h5>
        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-alert-triangle"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 9v4" /><path d="M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0z" /><path d="M12 16h.01" /></svg>
      </div>

      <div class="container-all-punishments">
        <% @group.punishments.each do  |punishment| %>
          <p>
            <%= punishment.name %>
          </p>
        <% end %>
      </div>


      <div data-controller="add-group-punishment" class="add-group-punishment">
        <button data-action="click->add-group-punishment#addPunishment" class="btn btn-primary button-punishment">
          Change Punishment
        </button>
        <div data-add-group-punishment-target="togglableElement" class="d-none">
          <% unless @punishment.nil? %>
            <%= render "shared/addnewpunishment", punishment: @punishment %>
          <% end %>
        </div>
    </div>
    </div>
  </section>
</section>