config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :groups do
    resources :members, only: [:create, :index, :edit] do
      resources :member_rewards, only: [:index, :update]
      resources :member_punishments, only: [:index, :update]
    end
    resources :rewards, only: [:index, :update]
    resources :punishments, only: [:index, :update]
    resources :tasks, only: [:new, :create]
    # resources :messages, only: [:show, :create]
  end

  resources :progresses, only: [:edit, :update]
  resources :members, only: [:show, :destroy, :edit]


  resources :chats, only: [:index, :show] do
    resources :messages, only: [:index, :show, :create]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_addnewpunishment.html.erb
<div class="div-container-simple-form-punishment">
  <%= simple_form_for [@group, @punishment], url: group_punishment_path(@group, @group.punishments[0].id), html: { class: "form-simple-punishment" }, method: :patch do |p| %>
    <%= p.input :name, required: true, placeholder: @group.punishments[0].name,
                input_html: { class: "center-placeholder" },
                label_html: { class: "label-punishment-name" },
                label: "New punishment" %>
    <%= p.hidden_field :group_id, value: @group.id %>
    <%= p.submit "Update punishment",class: "button-update-punishment" %>
  <% end %>
</div>

app/views/shared/_addnewreward.html.erb
<div class="div-container-simple-form-reward">
  <%= simple_form_for [@group, @reward], url: group_reward_path(@group, @group.rewards[0].id), html: { class: "form-simple-reward" }, method: :patch do |r| %>
    <%= r.input :name, required: true, placeholder: @group.rewards[0].name, 
                input_html: { class: "center-placeholder" }, 
                label_html: { class: "label-reward-name" },
                label: "New reward" %>
    <%= r.hidden_field :group_id, value: @group.id %>
    <%= r.submit "Update reward", class: "button-update-reward" %>
  <% end %>
</div>

app/views/shared/_addnewtask.html.erb
<div class="new-task">
<%= simple_form_for @task, html: { class: "form-newtask-showview" } ,url: group_tasks_path(@group) do |t| %>

  <div class="new-task-wrapper">
    <%= t.input :name, required: true, input_html: { placeholder: 'Run', class: 'center-placeholder', id: 'task-name' }, label: false %>
    <%= t.input :quantity, required: true, input_html: { placeholder: '10', class: 'center-placeholder', id: 'task-quantity' }, label: false %>
    <%= t.input :unit, required: true, input_html: { placeholder: 'Km', class: 'center-placeholder', id: 'task-unit' }, label: false %>
    <%= t.hidden_field :group_id, value: @group %>
  </div>

  <%= t.submit "Create Task", class: "btn btn-primary corpy-link-button-show-group", id:"new-task-button" %>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_linkShare.html.erb
<span class="button-share-link" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Invite
      <svg class="icon-share-link" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-share-2">
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path d="M8 9h-1a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-8a2 2 0 0 0 -2 -2h-1" />
        <path d="M12 14v-11" />
        <path d="M9 6l3 -3l3 3" />
      </svg>
</span>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-share-link-group">
    <div class="modal-content modal-contenido">
      
      <div class="header-modal-show-group">
        <h2 class="form-title">HaBet</h2>
        <p class="form-subtitle">Go further together</p>
      </div>

      <div class="title-group-show-modal">
        <div class="line-groups"></div>
        <h3 class="modal-title-show-group" id="exampleModalLabel">
          <%= @group.name %>
        </h3>
        <div class="line-groups"></div>
      </div>

      <div class="share-show-group-links">
        <span id="linkToCopy">
          <%= "https://habet-a528e90a741c.herokuapp.com/groups/#{@group.id}" %>
        </span>
        <button data-controller="toggle-copy-link" data-action="click->toggle-copy-link#copyLink" type="button" class="btn btn-primary corpy-link-button-show-group">Copy link</button>
        <button type="button" class="btn btn-secondary go-back-button-show-group" data-bs-dismiss="modal">Go back</button>
      </div>

    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_tabbar.html.erb
<nav id="tabbar-container">
  <%= link_to groups_path, class: "button_tabbar" do %>
    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-home"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12.707 2.293l9 9c.63 .63 .184 1.707 -.707 1.707h-1v6a3 3 0 0 1 -3 3h-1v-7a3 3 0 0 0 -2.824 -2.995l-.176 -.005h-2a3 3 0 0 0 -3 3v7h-1a3 3 0 0 1 -3 -3v-6h-1c-.89 0 -1.337 -1.077 -.707 -1.707l9 -9a1 1 0 0 1 1.414 0m.293 11.707a1 1 0 0 1 1 1v7h-4v-7a1 1 0 0 1 .883 -.993l.117 -.007z" /></svg>
  <% end %>

  <%= link_to chats_path, class: "button_tabbar" do %>

    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-message-circle"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5.821 4.91c3.899 -2.765 9.468 -2.539 13.073 .535c3.667 3.129 4.168 8.238 1.152 11.898c-2.841 3.447 -7.965 4.583 -12.231 2.805l-.233 -.101l-4.374 .931l-.04 .006l-.035 .007h-.018l-.022 .005h-.038l-.033 .004l-.021 -.001l-.023 .001l-.033 -.003h-.035l-.022 -.004l-.022 -.002l-.035 -.007l-.034 -.005l-.016 -.004l-.024 -.005l-.049 -.016l-.024 -.005l-.011 -.005l-.022 -.007l-.045 -.02l-.03 -.012l-.011 -.006l-.014 -.006l-.031 -.018l-.045 -.024l-.016 -.011l-.037 -.026l-.04 -.027l-.002 -.004l-.013 -.009l-.043 -.04l-.025 -.02l-.006 -.007l-.056 -.062l-.013 -.014l-.011 -.014l-.039 -.056l-.014 -.019l-.005 -.01l-.042 -.073l-.007 -.012l-.004 -.008l-.007 -.012l-.014 -.038l-.02 -.042l-.004 -.016l-.004 -.01l-.017 -.061l-.007 -.018l-.002 -.015l-.005 -.019l-.005 -.033l-.008 -.042l-.002 -.031l-.003 -.01v-.016l-.004 -.054l.001 -.036l.001 -.023l.002 -.053l.004 -.025v-.019l.008 -.035l.005 -.034l.005 -.02l.004 -.02l.018 -.06l.003 -.013l1.15 -3.45l-.022 -.037c-2.21 -3.747 -1.209 -8.391 2.413 -11.119z" /></svg>


    <div class="tabbar-count"><%= unread_message_count %></div>

  <% end %>

  <%= link_to new_group_path, class: "button_tabbar" do %>
    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-circle-plus"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4.929 4.929a10 10 0 1 1 14.141 14.141a10 10 0 0 1 -14.14 -14.14zm8.071 4.071a1 1 0 1 0 -2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0 -2h-2v-2z" /></svg>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to member_path(current_user.id), class: "button_tabbar" do %>
      <% if current_user.photo.present? && current_user.photo.key.present? %>
        <%= cl_image_tag(current_user.photo.key, class: "profileimg") %>
      <% else %>
        <i class="fa-solid fa-user"></i>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "button_tabbar" do %>
      <i class= "fas fa-user"></i>
  <% end %>
  <% end %>
</nav>