config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :groups do
    resources :members, only: [:create, :index, :edit] do
      resources :member_rewards, only: [:index, :update]
      resources :member_punishments, only: [:index, :update]
    end
    resources :rewards, only: [:index, :update]
    resources :punishments, only: [:index, :update]
    resources :tasks, only: [:new, :create]
    # resources :messages, only: [:show, :create]
  end

  resources :progresses, only: [:edit, :update]
  resources :members, only: [:show, :destroy, :edit]


  resources :chats, only: [:index, :show] do
    resources :messages, only: [:index, :show, :create]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :group
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @groups = Group.joins(:members).where(members: { user_id: current_user.id })
    @members = Member.where(user_id: current_user.id)
  end

  def show
    @chat = Chat.find(params[:chat_id])
    @messages = Message.where(group_id: @chat.group_id)
    @message = Message.new(group_id: @chat.group_id)
  end
end

app/views/chats/index.html.erb
<section class="chat-container-group">
<div class="section__title--groups">
  <div class="line-groups"></div>
    <h2 class="section__h2--groups">Your chats</h2>
  <div class="line-groups"></div>
</div>

<div class="container-chats">
<% @groups.each do |group| %>
  <div class="card-group">
    <% chat = Chat.find_by(group_id: group.id) %>
    <%= link_to chat_messages_path(chat.id), class: "card-group-title" do %>
    <% if group.photo.present? && group.photo.key.present? %>
      <%= cl_image_tag(group.photo.key, class: "picture-profile-group") %>
    <% else %>
      <%= image_tag "Držení Za Ruce.jfif", class: "picture-profile-group" %>
    <% end %>
    <div class="name-group-description">
      <h3><%= group.name %></h3>
    </div>

    <div class="count">
      <% member =  Member.find_by(user_id: current_user.id, group_id: group.id) %>
      <% messages = Message.where(chat_id: chat.id) %>
      <% reads = Read.where(member_id: member.id, message_id: messages.select(:id)) %>
      <% unreads = reads.count { |read| !read.read } %>
      <%=" #{unreads} " unless unreads.zero? %>
    </div>
  </div>
  <% end %>
<% end %>
</div>
</section>

app/views/chats/show.html.erb
<section class="chat-container-group">
  <div class="chat-title">
    <div class="line-groups"></div>
      <h2 class="section__h2--groups"><%= "#{@group.name}'s discussion" %></h2>
    <div class="line-groups"></div>
  </div>

  <div class="chat">
    <%= turbo_stream_from "group_#{@group.id}_messages" %>
    <div id="messages" class="message">
      <% @messages.each do |message| %>
        <%= render "messages/message", message: message, current_user_id: current_user.id %>
      <% end %>
    </div>
  </div>

  <div class="send">
  <%= form_with(model: [@group, @message], url: group_messages_path(@group)) do |f| %>
    <div class="send-wrapper">
    <%= f.text_field :content, placeholder: "Message", class:"message-field" %>
    <%= f.submit "Send", class:"send-button" %>
    </div>
  <% end %>
  </div>
</section>