config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :groups do
    resources :members, only: [:create, :index, :edit] do
      resources :member_rewards, only: [:index, :update]
      resources :member_punishments, only: [:index, :update]
    end
    resources :rewards, only: [:index, :update]
    resources :punishments, only: [:index, :update]
    resources :tasks, only: [:new, :create]
    # resources :messages, only: [:show, :create]
  end

  resources :progresses, only: [:edit, :update]
  resources :members, only: [:show, :destroy, :edit]


  resources :chats, only: [:index, :show] do
    resources :messages, only: [:index, :show, :create]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :progresses, dependent: :destroy
  has_many :reads, dependent: :destroy
  has_many :messages, dependent: :destroy

  ### added to make the pushinments and rewards tracking feacture
  has_many :member_punishments, dependent: :destroy
  has_many :punishments, through: :member_punishments
  has_many :member_rewards, dependent: :destroy
  has_many :rewards, through: :member_rewards
  has_one_attached :photo

  # validates :user_id, uniqueness: true
  # validates :group_id, uniqueness: true
  validates :user_id, uniqueness: { scope: :group_id, message: "Already in group" }

  COLORS = ["#AEC6CF", "#77DD77", "#F7C6C7", "#B39EB5", "#FDFD96", "#FFABAB", "#FFDAB9", "#B2DFDB", "#B2DFDB", "#B2DFDB"]

  before_create :assign_random_color

  def sorted_positions
    tasks = Task.where(group_id: group.id)
    ranking_calculation = RankingCalculation.new(tasks, group.id)
    ranking_calculation.position_table
  end

  private

  def assign_random_color
    self.color = COLORS.sample
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!

  def create
    @group = Group.find(params[:group_id])
    @member = Member.new
    @member.user = current_user
    @member.group = @group

    if @member.save
      # Assign existing punishments and rewards to the new member
      @group.punishments.each do |punishment|
        @member.member_punishments.create(punishment: punishment)
      end

      @group.rewards.each do |reward|
        @member.member_rewards.create(reward: reward)
      end

      ### Crea un progreso asignado al nuevo miembro para cada task en el grupo
      @group.tasks.each do |task|
        progress = Progress.new(task_id: task.id, member_id: @member.id, completion: 0.00)
        progress.save
      end

      ### Crea nuevo Read para cada mensage en el chat de grupo
      chat = Chat.find_by(group_id: @group.id)
      @messages = Message.where(chat_id: chat.id)
      @messages.each do |message|
        read = Read.new(message_id: message.id, member_id: @member.id)
        read.save
      end

      redirect_to group_path(@group)
    else
      render "groups/show", status: :unprocessable_entity
    end
  end

  def index
    @members = Member.where(group_id: params[:group_id])
    @group = @members.first.group
    @tasks = Task.where(group_id: params[:group_id])
    ranking_calculation = RankingCalculation.new(@tasks, params[:group_id])
    @progress = ranking_calculation.progress
    @sorted_positions = ranking_calculation.position_table
    @member_punishments = current_user.members.find_by(group_id: params[:group_id]).member_punishments.includes(:punishment)
    @member_rewards = current_user.members.find_by(group_id: params[:group_id]).member_rewards.includes(:reward)
  end

  def show
    @user = User.find(current_user.id)
    @tasks = @user.tasks
  end

  def destroy
    # 1. Delete the member
    @member = Member.find(params[:id])
    group = @member.group
    is_current_user = @member.user_id == current_user.id
    # 2. Delete the  member along their progresse because it have dependen destroy
    @member.destroy
    # 3. Redireccionar a la misma vista
    if is_current_user
      redirect_to groups_path
    else
      redirect_to group_members_path(group)
    end
  end
end

app/views/members/_incentives.html.erb
<section class="rewards-punishments-container">
  <div class="title-group-detail">
    <div class="line-groups"></div>
      <h3 class="title-group-detail-name">
        Incentives
      </h3>
    <div class="line-groups"></div>
  </div>

  <div class="target-rewards-container">
    <div class="container-title-reward">
      <h5 class="title-reward">
        Your Rewards
      </h5>
      <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-award"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 9m-6 0a6 6 0 1 0 12 0a6 6 0 1 0 -12 0" /><path d="M12 15l3.4 5.89l1.598 -3.233l3.598 .232l-3.4 -5.889" /><path d="M6.802 12l-3.4 5.89l3.598 -.233l1.598 3.232l3.4 -5.889" /></svg>
    </div>

    <div class="container-all-rewards">


      <div class="card my-3">
        <div class="card-body">
          <% if member_punishments.any? %>
            <% member_punishments.each do |mp| %>
              <div class="punishment-item">
                <strong><%= mp.punishment.name %></strong>
                <p>Status: <%= mp.status.capitalize %></p>
                <% if mp.pending? %>
                  <%= button_to 'Mark as Done', group_member_member_punishment_path(group, mp.member, mp), method: :patch, class: 'btn btn-warning btn-sm' %>
                <% end %>
              </div>
              <hr>
            <% end %>
          <% else %>
            <p>You have no punishments.</p>
          <% end %>
        </div>
      </div>


    </div>
  </div>

  <div class="target-punishments-container">
    <div class="container-title-punishment">
      <h5 class="title-punishment">
        Your Punishments
      </h5>
      <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-alert-triangle"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 9v4" /><path d="M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0z" /><path d="M12 16h.01" /></svg>
    </div>

    <div class="container-all-punishments">


      <div class="card my-3">
        <div class="card-body">
          <% if member_rewards.any? %>
            <% member_rewards.each do |mr| %>
              <div class="reward-item">
                <strong><%= mr.reward.name %></strong>
                <p>Status: <%= mr.status.capitalize %></p>
                <% if mr.available? %>
                  <%= button_to 'Claim Reward', group_member_member_reward_path(group, mr.member, mr), method: :patch, class: 'btn btn-success btn-sm' %>
                <% end %>
              </div>
              <hr>
            <% end %>
          <% else %>
            <p>You have no rewards.</p>
          <% end %>
        </div>
      </div>

    </div>





  </div>
</section>

app/views/members/_member_rank.html.erb
<div class="container-podium" id="app">
<div class="leaders">
  <ul id="topThreeList">

    <% if sorted_positions.length >= 2 %>
      <li class="podium-list">
        <div class="lead-cats">


          <% if sorted_positions[1][:user_id].photo.attached? %>
            <%= cl_image_tag(sorted_positions[1][:user_id].photo.key, class: "lead-cats__photo") %>
          <% else %>
            <i class="fa-solid fa-user lead-cats__photo text-center mb-2" style= "color: <%= Member.find_by(group_id: group_id, user_id: sorted_positions[1][:user_id]).color %>; font-size:60px"></i>
          <% end %>
          <div class="podium pod-3">
              <div class="ranking-lead">2</div>
              <h4><%= sorted_positions[1][:username] %></h4>
              <p class="podium-advance"><%= (sorted_positions[1][:average_progress]*100).round(2) %>%</p>
          </div>
        </div>
      </li>
    <% end %>


    <li class="podium-list">
      <div class="lead-cats">

        <% if sorted_positions[0][:user_id].photo.attached? %>
          <%= cl_image_tag(sorted_positions[0][:user_id].photo.key, class: "lead-cats__photo") %>
        <% else %>
          <i class="fa-solid fa-user lead-cats__photo text-center mb-2" style= "color: <%= Member.find_by(group_id: group_id, user_id: sorted_positions[0][:user_id]).color %>; font-size:60px"></i>
        <% end %>
        <div class="podium pod-2">
            <div class="ranking-lead">1</div>
            <h4><%= sorted_positions[0][:username] %></h4>
            <p class="podium-advance"><%= (sorted_positions[0][:average_progress]*100).round(2) %>%</p>
        </div>
      </div>
    </li>

    <% if sorted_positions.length >= 3 %>
      <li class="podium-list">
        <div class="lead-cats">

          

          <% if sorted_positions[2][:user_id].photo.attached? %>
            <%= cl_image_tag(sorted_positions[2][:user_id].photo.key, class: "lead-cats__photo") %>
          <% else %>
            <i class="fa-solid fa-user lead-cats__photo text-center mb-2" style= "color: <%= Member.find_by(group_id: group_id, user_id: sorted_positions[2][:user_id]).color %>; font-size:60px"></i>
          <% end %>
          <div class="podium pod-1">
              <div class="ranking-lead">3</div>
              <h4><%= sorted_positions[2][:username] %></h4>
              <p class="podium-advance"><%= (sorted_positions[2][:average_progress]*100).round(2) %>%</p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>


<div class="board <%= "d-none" if sorted_positions.length < 4 %>">
  <ul id="leaderboard">
    <% sorted_positions.each_with_index do |user, index| %>
      <% if index >= 3 %>
        <li class="cat-item" data-edit-members-target="memberCard">

          <div class="cat-item__photo">
            <div class="ranking"><%= user[:rank] %>th</div>
            <% if user[:user_id].photo.attached? %>
              <%= cl_image_tag(user[:user_id].photo.key) %>
            <% else %>
              <i class="fa-solid fa-user" style= "color: <%= Member.find_by(group_id: group_id, user_id: user[:user_id]).color %>; font-size:40px"></i>
            <% end %>
          </div>

          <div class="cat-item__info">
            <h4><%= user[:username] %></h4>
            <div class="cat-item__points">
              <div class="progress-bar bar-members" role="progressbar" style="width: <%= user[:average_progress]*100.round(2) %>%; min-width: min-content;">
                <% if user[:average_progress]*100 < 20  %>
                  <%= (user[:average_progress]*100).round(0) %>%
                <% else %>
                  <%= (user[:average_progress]*100).round(2) %>%
                <% end %>
              </div>
            </div>
          </div>


        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/members/index.html.erb
<section class="section-index-members" data-controller="edit-members">

  <div class="title-member-detail">
    <div class="line-members"></div>
      <h3 class="title-member-detail-name">
        <%= @group.name %>
      </h3>
    <div class="line-members"></div>
  </div>

  <div class="members-rank-title">
    <h2>Members Rank</h2>
  </div>

  <div class="members-list">

    <%= turbo_stream_from "group_#{@group.id}_rank" %>
    <div id="group_ranking" class="w-100">
      <%= render 'member_rank', sorted_positions: @sorted_positions, member_user: current_user, group_id: @group.id %>
    </div>

    <!-- <div class="toggable-section d-none" data-edit-members-target="toggable">
      <div data-controller="group-member" data-group-member-group-id-value="<%= @group.id %>">
        <div class="row justify-content-end">
          <div class="w-50 py-2">
            <%= render 'shared/linkShare' %>
          </div>
        </div>
      </div>
    </div>

    <% if current_user.members.find_by(group_id: params[:group_id]).admin %>
      <button class="delete-members-button btn btn-primary my-2" data-action="click->edit-members#toggleEdits" data-edit-members-target="editButton">
        Delete members
      </button>
    <% end %>
    -->
  </div>

</section>

app/views/members/show.html.erb
<section class="section-index-groups">
  <div class="section__title--groups">
    <div class="line-groups"></div>
      <h2 class="section__h2--groups">Your Profile</h2>
    <div class="line-groups"></div>
  </div>

  <section class="the-profile">
    <div class="profile-desc">
    <% if current_user.photo.present? && current_user.photo.key.present? %>
      <%= cl_image_tag(current_user.photo.key, class: "profile-picture") %>
    <% else %>
      <%= image_tag "user-solid.svg", class: "profile-picture" %>
    <% end %>

    <div class="profile-text">
      <h3><%= @user.username %></h3>
      <h5><%= @user.first_name %> <%= @user.last_name %></h5>
    </div>
  </div>


    <% progress_sum = 0 %>
    <% @tasks.each do |t| %>
      <% sum = t.total_progress(@user) %>
      <% progress_sum += sum %>
    <% end %>


    <div class="progress-profile">
      <h5>Total Progress: </h5>
      <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: <%= [[(progress_sum || 0).round(2), 100].min, 0].max %>%;">
          <%= (progress_sum || 0).round(2) %> %
        </div>
      </div>
    </div>

    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-edit" %>
    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-logout" %>
  </section>
  
</section>